INSERT INTO TEAM(team_name, award_count) values ('서울', 18);
INSERT INTO TEAM(team_name, award_count) values ('대전', 3);
INSERT INTO TEAM(team_name, award_count) values ('부산', 10);
INSERT INTO TEAM(team_name, award_count) values ('로스앤젤레스', 4);
INSERT INTO TEAM(team_name, award_count) values ('워싱턴', 7);
INSERT INTO TEAM(team_name, award_count) values ('뉴욕', 6);
INSERT INTO TEAM(team_name, award_count) values ('라스베이거스', 9);
INSERT INTO TEAM(team_name, award_count) values ('타이완', 3);
INSERT INTO TEAM(team_name, award_count) values ('도쿄', 1);
INSERT INTO TEAM(team_name, award_count) values ('상하이', 12);
INSERT INTO TEAM(team_name, award_count) values ('홍콩', 9);
INSERT INTO TEAM(team_name, award_count) values ('항저우', 5);
INSERT INTO TEAM(team_name, award_count) values ('대구', 14);
INSERT INTO TEAM(team_name, award_count) values ('속초', 11);
INSERT INTO TEAM(team_name, award_count) values ('광주', 8);


INSERT INTO MEMBER(name, age, team_id) values('아이유', 27, 1);
INSERT INTO MEMBER(name, age, team_id) values('레드벨벳', 24, 1);
INSERT INTO MEMBER(name, age, team_id) values('악동뮤지션', 21, 1);
INSERT INTO MEMBER(name, age, team_id) values('윤하', 22, 1);
INSERT INTO MEMBER(name, age, team_id) values('소녀시대', 12, 1);
INSERT INTO MEMBER(name, age, team_id) values('제이플라', 15, 1);
INSERT INTO MEMBER(name, age, team_id) values('비투비', 30, 2);
INSERT INTO MEMBER(name, age, team_id) values('악동뮤지션', 18, 5);
INSERT INTO MEMBER(name, age, team_id) values('씨야', 12, 4);
INSERT INTO MEMBER(name, age, team_id) values('방탄소년단', 26, 13);
INSERT INTO MEMBER(name, age, team_id) values('윤종신', 36, 12);
INSERT INTO MEMBER(name, age, team_id) values('마마무', 31, 8);
INSERT INTO MEMBER(name, age, team_id) values('트와이스', 19, 7);
INSERT INTO MEMBER(name, age, team_id) values('엑소', 33, 9);
INSERT INTO MEMBER(name, age, team_id) values('태연', 32, 9);
INSERT INTO MEMBER(name, age, team_id) values('멜로망', 16, 10);
INSERT INTO MEMBER(name, age, team_id) values('백아연', 32, 6);
INSERT INTO MEMBER(name, age, team_id) values('정승환', 23, 6);
INSERT INTO MEMBER(name, age, team_id) values('벤', 20, 7);
INSERT INTO MEMBER(name, age, team_id) values('럼블피쉬', 35, 8);
INSERT INTO MEMBER(name, age, team_id) values('이수', 15, 15);
INSERT INTO MEMBER(name, age, team_id) values('임재현', 38, 14);
